[tool.poetry]
name = "ai2024-hw2"
version = "0.1.0"
description = ""
authors = ["AI_vv"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
